/* A recursive-descent parser generated by peg 0.1.2 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define YYRULECOUNT 43

#include <stdio.h>
#include <signal.h>
#include <time.h>
#include <stdarg.h>

#define YY_noDEBUG 1
#define KBYTE 1024
#define MBYTE KBYTE * 1024

int current_header_level;
int current_bullet_list_level;
int current_numbered_list_level;
int start_of_line = 1;
char protocol[5];

char *space_to_underscore(char *s, size_t size) {
	char *temp = (char *)malloc(size);
	for(int i = 0; i < size; i++) {
		if(s[i] == ' ' && i != size-1) {
			temp[i] = '_';
		} else {
			temp[i] = s[i];
		}
	}
	return temp;
}

int in_tag = 0;
char *tag_content;
unsigned int tag_content_length = 0;
unsigned int tag_content_size = 2 * MBYTE;

void open_tag(char *tag, char *args) {
	if(args) {
		printf("<%s %s>", tag, args);
	} else {
		printf("<%s>", tag);
	}
	
	in_tag = 1;
	free(tag_content);
	tag_content = malloc(tag_content_size);
}

void close_tag(char *tag) {
	printf("</%s>", tag);
	in_tag = 0;
}

void append_to_tag_content(char *c, size_t s) {
	if(!in_tag) return;
	if(s + tag_content_length > tag_content_size) {
		tag_content_size *= 2;
		tag_content = realloc(tag_content, tag_content_size);
	}
	
	memcpy(tag_content + tag_content_length, c, s);
	tag_content_length += s;
	tag_content[tag_content_length] = 0;
}


#ifndef YY_VARIABLE
#define YY_VARIABLE(T)	static T
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( yybegin= yypos, 1)
#endif
#ifndef YY_END
#define YY_END		( yyend= yypos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args)	fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE	int
#endif

#ifndef YY_PART

typedef void (*yyaction)(char *yytext, int yyleng);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

YY_VARIABLE(char *   ) yybuf= 0;
YY_VARIABLE(int	     ) yybuflen= 0;
YY_VARIABLE(int	     ) yypos= 0;
YY_VARIABLE(int	     ) yylimit= 0;
YY_VARIABLE(char *   ) yytext= 0;
YY_VARIABLE(int	     ) yytextlen= 0;
YY_VARIABLE(int	     ) yybegin= 0;
YY_VARIABLE(int	     ) yyend= 0;
YY_VARIABLE(int	     ) yytextmax= 0;
YY_VARIABLE(yythunk *) yythunks= 0;
YY_VARIABLE(int	     ) yythunkslen= 0;
YY_VARIABLE(int      ) yythunkpos= 0;
YY_VARIABLE(YYSTYPE  ) yy;
YY_VARIABLE(YYSTYPE *) yyval= 0;
YY_VARIABLE(YYSTYPE *) yyvals= 0;
YY_VARIABLE(int      ) yyvalslen= 0;

YY_LOCAL(int) yyrefill(void)
{
  int yyn;
  while (yybuflen - yypos < 512)
    {
      yybuflen *= 2;
      yybuf= realloc(yybuf, yybuflen);
    }
  YY_INPUT((yybuf + yypos), yyn, (yybuflen - yypos));
  if (!yyn) return 0;
  yylimit += yyn;
  return 1;
}

static char* yyunmatched(void) {
	static char copy[45];
	int pos = 0;
	while (pos < 40) {
		if (yypos+pos >= yylimit) break;
		char ch = yybuf[yypos+pos];
		if (ch == '\n') {
			copy[pos++] = '\\';
			copy[pos++] = 'n';
			break;
		}
		copy[pos++] = ch;
	}
	if (yypos+pos < yylimit) {
		copy[pos++]='.';
		copy[pos++]='.';
		copy[pos++]='.';
	}
	copy[pos] = '\0';
	return copy;
}

YY_LOCAL(int) yymatchDot(void)
{
  if (yypos >= yylimit && !yyrefill()) return 0;
  ++yypos;
  return 1;
}

YY_LOCAL(int) yymatchChar(int c)
{
  if (yypos >= yylimit && !yyrefill()) return 0;
  if (yybuf[yypos] == c)
    {
      ++yypos;
      yyprintf((stderr, "  ok   yymatchChar(%c) @ %s\n", c, yyunmatched()));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(%c) @ %s\n", c, yyunmatched()));
  return 0;
}

YY_LOCAL(int) yymatchString(char *s)
{
  int yysav= yypos;
  while (*s)
    {
      if (yypos >= yylimit && !yyrefill()) return 0;
      if (yybuf[yypos] != *s)
        {
          yypos= yysav;
          return 0;
        }
      ++s;
      ++yypos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(unsigned char *bits)
{
  int c;
  if (yypos >= yylimit && !yyrefill()) return 0;
  c= yybuf[yypos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++yypos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", yyunmatched()));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", yyunmatched()));
  return 0;
}

YY_LOCAL(void) yyDo(yyaction action, int begin, int end)
{
  while (yythunkpos >= yythunkslen)
    {
      yythunkslen *= 2;
      yythunks= realloc(yythunks, sizeof(yythunk) * yythunkslen);
    }
  yythunks[yythunkpos].begin=  begin;
  yythunks[yythunkpos].end=    end;
  yythunks[yythunkpos].action= action;
  ++yythunkpos;
}

YY_LOCAL(int) yyText(int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (yytextlen < (yyleng - 1))
	{
	  yytextlen *= 2;
	  yytext= realloc(yytext, yytextlen);
	}
      memcpy(yytext, yybuf + begin, yyleng);
    }
  yytext[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(void)
{
  int pos;
  for (pos= 0;  pos < yythunkpos;  ++pos)
    {
      yythunk *thunk= &yythunks[pos];
      int yyleng= thunk->end ? yyText(thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, yytext));
      thunk->action(yytext, yyleng);
    }
  yythunkpos= 0;
}

YY_LOCAL(void) yyCommit()
{
  if ((yylimit -= yypos))
    {
      memmove(yybuf, yybuf + yypos, yylimit);
    }
  yybegin -= yypos;
  yyend -= yypos;
  yypos= yythunkpos= 0;
}

YY_LOCAL(int) yyAccept(int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone();
      yyCommit();
    }
  return 1;
}

YY_LOCAL(void) yyPush(char *text, int count)	{ yyval += count; }
YY_LOCAL(void) yyPop(char *text, int count)	{ yyval -= count; }
YY_LOCAL(void) yySet(char *text, int count)	{ yyval[count]= yy; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(yythunkpos0)

YY_RULE(int) yy_table_cell(); /* 43 */
YY_RULE(int) yy_table_heading(); /* 42 */
YY_RULE(int) yy_table_row(); /* 41 */
YY_RULE(int) yy_table_header(); /* 40 */
YY_RULE(int) yy_table_caption(); /* 39 */
YY_RULE(int) yy_table_body(); /* 38 */
YY_RULE(int) yy_plain_image(); /* 37 */
YY_RULE(int) yy_image_with_alt(); /* 36 */
YY_RULE(int) yy_link_name(); /* 35 */
YY_RULE(int) yy_link_url(); /* 34 */
YY_RULE(int) yy_url(); /* 33 */
YY_RULE(int) yy_unnamed_link(); /* 32 */
YY_RULE(int) yy_named_link(); /* 31 */
YY_RULE(int) yy_external_link(); /* 30 */
YY_RULE(int) yy_simple_link(); /* 29 */
YY_RULE(int) yy_renamed_link(); /* 28 */
YY_RULE(int) yy_pre_line(); /* 27 */
YY_RULE(int) yy_italic(); /* 26 */
YY_RULE(int) yy_bold(); /* 25 */
YY_RULE(int) yy_bold_italic(); /* 24 */
YY_RULE(int) yy_numbered(); /* 23 */
YY_RULE(int) yy_numbered_list_entry(); /* 22 */
YY_RULE(int) yy_bullet(); /* 21 */
YY_RULE(int) yy_bullet_list_entry(); /* 20 */
YY_RULE(int) yy_numbered_list(); /* 19 */
YY_RULE(int) yy_bullet_list(); /* 18 */
YY_RULE(int) yy_heading_text(); /* 17 */
YY_RULE(int) yy_heading_marker(); /* 16 */
YY_RULE(int) yy_eol(); /* 15 */
YY_RULE(int) yy_anything_else(); /* 14 */
YY_RULE(int) yy_table(); /* 13 */
YY_RULE(int) yy_link(); /* 12 */
YY_RULE(int) yy_image(); /* 11 */
YY_RULE(int) yy_formatting(); /* 10 */
YY_RULE(int) yy_list(); /* 9 */
YY_RULE(int) yy_indentation(); /* 8 */
YY_RULE(int) yy_heading(); /* 7 */
YY_RULE(int) yy_horizontal_line(); /* 6 */
YY_RULE(int) yy_paragraph(); /* 5 */
YY_RULE(int) yy_wikitext(); /* 4 */
YY_RULE(int) yy_wikitext_line(); /* 3 */
YY_RULE(int) yy_pre_block(); /* 2 */
YY_RULE(int) yy_page(); /* 1 */

YY_ACTION(void) yy_1_anything_else(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_anything_else\n"));
   start_of_line = 0; printf("%s", yytext); if(in_tag) { append_to_tag_content(yytext, yyleng); } ;
}
YY_ACTION(void) yy_3_table_heading(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_3_table_heading\n"));
  printf("%s</th>", yytext); ;
}
YY_ACTION(void) yy_2_table_heading(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_table_heading\n"));
   printf(" %s>", yytext); ;
}
YY_ACTION(void) yy_1_table_heading(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_table_heading\n"));
   printf("<th"); ;
}
YY_ACTION(void) yy_2_table_header(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_table_header\n"));
   printf("</tr>"); ;
}
YY_ACTION(void) yy_1_table_header(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_table_header\n"));
   printf("<tr>"); ;
}
YY_ACTION(void) yy_2_table_cell(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_table_cell\n"));
   printf("%s</td>", yytext); ;
}
YY_ACTION(void) yy_1_table_cell(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_table_cell\n"));
   printf("<td>"); ;
}
YY_ACTION(void) yy_2_table_row(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_table_row\n"));
   printf("</tr>"); ;
}
YY_ACTION(void) yy_1_table_row(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_table_row\n"));
   printf("<tr>"); ;
}
YY_ACTION(void) yy_1_table_caption(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_table_caption\n"));
   printf("<caption>%s</caption>", yytext); ;
}
YY_ACTION(void) yy_2_table(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_table\n"));
   printf("</table>"); ;
}
YY_ACTION(void) yy_1_table(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_table\n"));
   printf("<table>"); ;
}
YY_ACTION(void) yy_2_image_with_alt(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_image_with_alt\n"));
   printf(" alt=\"%s\" />", yytext); ;
}
YY_ACTION(void) yy_1_image_with_alt(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_image_with_alt\n"));
   printf("<img src=\"%s\"", yytext ); ;
}
YY_ACTION(void) yy_1_plain_image(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_plain_image\n"));
   printf("<img src=\"%s\" />", yytext); ;
}
YY_ACTION(void) yy_2_url(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_url\n"));
   printf("<a href=\"%s://%s\">%s://%s</a>", protocol, yytext, protocol, yytext); ;
}
YY_ACTION(void) yy_1_url(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_url\n"));
   strcpy(protocol, yytext); ;
}
YY_ACTION(void) yy_1_unnamed_link(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_unnamed_link\n"));
   printf("<a href=\"%s\">%s</a>", yytext, yytext);;
}
YY_ACTION(void) yy_1_link_name(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_link_name\n"));
   printf("%s", yytext); ;
}
YY_ACTION(void) yy_1_link_url(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_link_url\n"));
   printf("%s", yytext); ;
}
YY_ACTION(void) yy_3_named_link(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_3_named_link\n"));
  printf("</a>");;
}
YY_ACTION(void) yy_2_named_link(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_named_link\n"));
  printf("\">");;
}
YY_ACTION(void) yy_1_named_link(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_named_link\n"));
  printf("<a href=\""); ;
}
YY_ACTION(void) yy_2_renamed_link(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_renamed_link\n"));
   printf("%s</a>", yytext); ;
}
YY_ACTION(void) yy_1_renamed_link(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_renamed_link\n"));
   
	char *path = space_to_underscore(yytext, yyleng);
	printf("<a href=\"/%s\">", path);
	free(path);
	;
}
YY_ACTION(void) yy_2_simple_link(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_simple_link\n"));
   printf("%s</a>", yytext); ;
}
YY_ACTION(void) yy_1_simple_link(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_simple_link\n"));
  
	char *path = space_to_underscore(yytext, yyleng);
	printf("<a href=\"/%s\">%s", path, yytext);
	free(path);
	;
}
YY_ACTION(void) yy_1_pre_line(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_pre_line\n"));
   printf("%s", yytext); ;
}
YY_ACTION(void) yy_2_pre_block(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_pre_block\n"));
   printf("</pre>"); ;
}
YY_ACTION(void) yy_1_pre_block(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_pre_block\n"));
   printf("<pre>"); ;
}
YY_ACTION(void) yy_2_italic(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_italic\n"));
  printf("</i>");;
}
YY_ACTION(void) yy_1_italic(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_italic\n"));
  printf("<i>");;
}
YY_ACTION(void) yy_2_bold(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_bold\n"));
  printf("</b>");;
}
YY_ACTION(void) yy_1_bold(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_bold\n"));
  printf("<b>");;
}
YY_ACTION(void) yy_2_bold_italic(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_bold_italic\n"));
  printf("</i></b>");;
}
YY_ACTION(void) yy_1_bold_italic(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_bold_italic\n"));
  printf("<b><i>");;
}
YY_ACTION(void) yy_1_numbered(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_numbered\n"));
  
	start_of_line = 0;
	if(current_numbered_list_level < yyleng && current_numbered_list_level != 0) {
		printf("<ol>");
	} else if(current_numbered_list_level > yyleng) {
		printf("</ol>");
	}
	current_numbered_list_level = yyleng; 
	printf("<li>"); 
;
}
YY_ACTION(void) yy_1_numbered_list_entry(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_numbered_list_entry\n"));
   printf("</li>"); ;
}
YY_ACTION(void) yy_2_numbered_list(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_numbered_list\n"));
   while(current_numbered_list_level--) { printf("</ol>"); } ;
}
YY_ACTION(void) yy_1_numbered_list(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_numbered_list\n"));
   printf("<ol>"); ;
}
YY_ACTION(void) yy_1_bullet(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_bullet\n"));
  
	start_of_line = 0;
	if(current_bullet_list_level < yyleng && current_bullet_list_level != 0) {
		printf("<ul>");
	} else if(current_bullet_list_level > yyleng) {
		printf("</ul>");
	}
	current_bullet_list_level = yyleng; 
	printf("<li>"); 
;
}
YY_ACTION(void) yy_1_bullet_list_entry(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_bullet_list_entry\n"));
   printf("</li>"); ;
}
YY_ACTION(void) yy_2_bullet_list(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_bullet_list\n"));
   while(current_bullet_list_level--) { printf("</ul>"); } ;
}
YY_ACTION(void) yy_1_bullet_list(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_bullet_list\n"));
   printf("<ul>"); ;
}
YY_ACTION(void) yy_1_indentation(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_indentation\n"));
   printf("&nbsp;&nbsp;"); ;
}
YY_ACTION(void) yy_1_horizontal_line(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_horizontal_line\n"));
   printf("<hr/>"); ;
}
YY_ACTION(void) yy_2_paragraph(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_paragraph\n"));
   printf("</p>"); ;
}
YY_ACTION(void) yy_1_paragraph(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_paragraph\n"));
   printf("<p>"); ;
}
YY_ACTION(void) yy_1_heading_marker(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_heading_marker\n"));
   current_header_level = yyleng - 1; ;
}
YY_ACTION(void) yy_1_heading_text(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_heading_text\n"));
   printf("<a name=\"%s\" />", space_to_underscore(tag_content, tag_content_length)); ;
}
YY_ACTION(void) yy_2_heading(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_heading\n"));
  
		char tag[4];
		sprintf(tag, "h%d", current_header_level);
		close_tag(tag);
	;
}
YY_ACTION(void) yy_1_heading(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_heading\n"));
  
		char tag[4];
		sprintf(tag, "h%d", current_header_level);
		open_tag(tag, NULL);
	;
}
YY_ACTION(void) yy_1_eol(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_eol\n"));
   start_of_line = 1; ;
}

YY_RULE(int) yy_table_cell()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "table_cell"));
  {  int yypos2= yypos, yythunkpos2= yythunkpos;  if (!yymatchChar('|')) goto l2;  goto l3;
  l2:;	  yypos= yypos2; yythunkpos= yythunkpos2;
  }
  l3:;	  yyDo(yy_1_table_cell, yybegin, yyend);  if (!yymatchChar(' ')) goto l1;
  l4:;	
  {  int yypos5= yypos, yythunkpos5= yythunkpos;  if (!yymatchChar(' ')) goto l5;  goto l4;
  l5:;	  yypos= yypos5; yythunkpos= yythunkpos5;
  }  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l1;
  l6:;	
  {  int yypos7= yypos, yythunkpos7= yythunkpos;
  {  int yypos8= yypos, yythunkpos8= yythunkpos;  if (!yymatchString("||")) goto l8;  goto l7;
  l8:;	  yypos= yypos8; yythunkpos= yythunkpos8;
  }
  {  int yypos9= yypos, yythunkpos9= yythunkpos;  if (!yy_eol()) goto l9;  goto l7;
  l9:;	  yypos= yypos9; yythunkpos= yythunkpos9;
  }  if (!yymatchDot()) goto l7;  goto l6;
  l7:;	  yypos= yypos7; yythunkpos= yythunkpos7;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l1;
  {  int yypos10= yypos, yythunkpos10= yythunkpos;  if (!yy_eol()) goto l11;  goto l10;
  l11:;	  yypos= yypos10; yythunkpos= yythunkpos10;  if (!yymatchString("||")) goto l1;
  }
  l10:;	  yyDo(yy_2_table_cell, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "table_cell", yyunmatched()));
  return 1;
  l1:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "table_cell", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_table_heading()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "table_heading"));  yyDo(yy_1_table_heading, yybegin, yyend);  if (!yymatchChar('!')) goto l12;  if (!yymatchChar(' ')) goto l12;
  l13:;	
  {  int yypos14= yypos, yythunkpos14= yythunkpos;  if (!yymatchChar(' ')) goto l14;  goto l13;
  l14:;	  yypos= yypos14; yythunkpos= yythunkpos14;
  }  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l12;
  l15:;	
  {  int yypos16= yypos, yythunkpos16= yythunkpos;
  {  int yypos17= yypos, yythunkpos17= yythunkpos;  if (!yymatchString(" |")) goto l17;  goto l16;
  l17:;	  yypos= yypos17; yythunkpos= yythunkpos17;
  }  if (!yymatchDot()) goto l16;  goto l15;
  l16:;	  yypos= yypos16; yythunkpos= yythunkpos16;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l12;  yyDo(yy_2_table_heading, yybegin, yyend);  if (!yymatchString(" |")) goto l12;
  l18:;	
  {  int yypos19= yypos, yythunkpos19= yythunkpos;  if (!yymatchChar(' ')) goto l19;  goto l18;
  l19:;	  yypos= yypos19; yythunkpos= yythunkpos19;
  }  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l12;
  l20:;	
  {  int yypos21= yypos, yythunkpos21= yythunkpos;
  {  int yypos22= yypos, yythunkpos22= yythunkpos;  if (!yy_eol()) goto l22;  goto l21;
  l22:;	  yypos= yypos22; yythunkpos= yythunkpos22;
  }  if (!yymatchDot()) goto l21;  goto l20;
  l21:;	  yypos= yypos21; yythunkpos= yythunkpos21;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l12;  if (!yy_eol()) goto l12;  yyDo(yy_3_table_heading, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "table_heading", yyunmatched()));
  return 1;
  l12:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "table_heading", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_table_row()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "table_row"));  if (!yymatchString("|-")) goto l23;  yyDo(yy_1_table_row, yybegin, yyend);
  l24:;	
  {  int yypos25= yypos, yythunkpos25= yythunkpos;  if (!yymatchChar(' ')) goto l25;  goto l24;
  l25:;	  yypos= yypos25; yythunkpos= yythunkpos25;
  }  if (!yy_eol()) goto l23;
  l26:;	
  {  int yypos27= yypos, yythunkpos27= yythunkpos;  if (!yy_table_heading()) goto l27;  goto l26;
  l27:;	  yypos= yypos27; yythunkpos= yythunkpos27;
  }
  l28:;	
  {  int yypos29= yypos, yythunkpos29= yythunkpos;  if (!yy_table_cell()) goto l29;  goto l28;
  l29:;	  yypos= yypos29; yythunkpos= yythunkpos29;
  }  yyDo(yy_2_table_row, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "table_row", yyunmatched()));
  return 1;
  l23:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "table_row", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_table_header()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "table_header"));  yyDo(yy_1_table_header, yybegin, yyend);  if (!yy_table_heading()) goto l30;
  l31:;	
  {  int yypos32= yypos, yythunkpos32= yythunkpos;  if (!yy_table_heading()) goto l32;  goto l31;
  l32:;	  yypos= yypos32; yythunkpos= yythunkpos32;
  }  yyDo(yy_2_table_header, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "table_header", yyunmatched()));
  return 1;
  l30:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "table_header", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_table_caption()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "table_caption"));  if (!yymatchString("|+")) goto l33;  if (!yymatchChar(' ')) goto l33;
  l34:;	
  {  int yypos35= yypos, yythunkpos35= yythunkpos;  if (!yymatchChar(' ')) goto l35;  goto l34;
  l35:;	  yypos= yypos35; yythunkpos= yythunkpos35;
  }  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l33;
  l36:;	
  {  int yypos37= yypos, yythunkpos37= yythunkpos;
  {  int yypos38= yypos, yythunkpos38= yythunkpos;  if (!yy_eol()) goto l38;  goto l37;
  l38:;	  yypos= yypos38; yythunkpos= yythunkpos38;
  }  if (!yymatchDot()) goto l37;  goto l36;
  l37:;	  yypos= yypos37; yythunkpos= yythunkpos37;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l33;  if (!yy_eol()) goto l33;  yyDo(yy_1_table_caption, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "table_caption", yyunmatched()));
  return 1;
  l33:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "table_caption", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_table_body()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "table_body"));
  {  int yypos40= yypos, yythunkpos40= yythunkpos;  if (!yy_table_caption()) goto l40;  goto l41;
  l40:;	  yypos= yypos40; yythunkpos= yythunkpos40;
  }
  l41:;	
  {  int yypos42= yypos, yythunkpos42= yythunkpos;  if (!yy_table_header()) goto l42;  goto l43;
  l42:;	  yypos= yypos42; yythunkpos= yythunkpos42;
  }
  l43:;	  if (!yy_table_row()) goto l39;
  l44:;	
  {  int yypos45= yypos, yythunkpos45= yythunkpos;  if (!yy_table_row()) goto l45;  goto l44;
  l45:;	  yypos= yypos45; yythunkpos= yythunkpos45;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "table_body", yyunmatched()));
  return 1;
  l39:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "table_body", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_plain_image()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "plain_image"));  if (!yymatchString("[[")) goto l46;
  l47:;	
  {  int yypos48= yypos, yythunkpos48= yythunkpos;  if (!yymatchChar(' ')) goto l48;  goto l47;
  l48:;	  yypos= yypos48; yythunkpos= yythunkpos48;
  }  if (!yymatchString("File:")) goto l46;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l46;
  l49:;	
  {  int yypos50= yypos, yythunkpos50= yythunkpos;
  {  int yypos51= yypos, yythunkpos51= yythunkpos;  if (!yymatchString("]]")) goto l51;  goto l50;
  l51:;	  yypos= yypos51; yythunkpos= yythunkpos51;
  }  if (!yymatchDot()) goto l50;  goto l49;
  l50:;	  yypos= yypos50; yythunkpos= yythunkpos50;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l46;
  l52:;	
  {  int yypos53= yypos, yythunkpos53= yythunkpos;  if (!yymatchChar(' ')) goto l53;  goto l52;
  l53:;	  yypos= yypos53; yythunkpos= yythunkpos53;
  }  if (!yymatchString("]]")) goto l46;  yyDo(yy_1_plain_image, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "plain_image", yyunmatched()));
  return 1;
  l46:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "plain_image", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_image_with_alt()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "image_with_alt"));  if (!yymatchString("[[")) goto l54;
  l55:;	
  {  int yypos56= yypos, yythunkpos56= yythunkpos;  if (!yymatchChar(' ')) goto l56;  goto l55;
  l56:;	  yypos= yypos56; yythunkpos= yythunkpos56;
  }  if (!yymatchString("File:")) goto l54;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l54;
  l57:;	
  {  int yypos58= yypos, yythunkpos58= yythunkpos;
  {  int yypos59= yypos, yythunkpos59= yythunkpos;  if (!yymatchChar('|')) goto l59;  goto l58;
  l59:;	  yypos= yypos59; yythunkpos= yythunkpos59;
  }  if (!yymatchDot()) goto l58;  goto l57;
  l58:;	  yypos= yypos58; yythunkpos= yythunkpos58;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l54;  yyDo(yy_1_image_with_alt, yybegin, yyend);  if (!yymatchString("|alt=")) goto l54;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l54;
  l60:;	
  {  int yypos61= yypos, yythunkpos61= yythunkpos;
  {  int yypos62= yypos, yythunkpos62= yythunkpos;  if (!yymatchString("]]")) goto l62;  goto l61;
  l62:;	  yypos= yypos62; yythunkpos= yythunkpos62;
  }  if (!yymatchDot()) goto l61;  goto l60;
  l61:;	  yypos= yypos61; yythunkpos= yythunkpos61;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l54;  yyDo(yy_2_image_with_alt, yybegin, yyend);  if (!yymatchString("]]")) goto l54;
  yyprintf((stderr, "  ok   %s @ %s\n", "image_with_alt", yyunmatched()));
  return 1;
  l54:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "image_with_alt", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_link_name()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "link_name"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l63;
  {  int yypos66= yypos, yythunkpos66= yythunkpos;  if (!yymatchChar(']')) goto l66;  goto l63;
  l66:;	  yypos= yypos66; yythunkpos= yythunkpos66;
  }  if (!yymatchDot()) goto l63;
  l64:;	
  {  int yypos65= yypos, yythunkpos65= yythunkpos;
  {  int yypos67= yypos, yythunkpos67= yythunkpos;  if (!yymatchChar(']')) goto l67;  goto l65;
  l67:;	  yypos= yypos67; yythunkpos= yythunkpos67;
  }  if (!yymatchDot()) goto l65;  goto l64;
  l65:;	  yypos= yypos65; yythunkpos= yythunkpos65;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l63;  yyDo(yy_1_link_name, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "link_name", yyunmatched()));
  return 1;
  l63:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "link_name", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_link_url()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "link_url"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l68;
  {  int yypos71= yypos, yythunkpos71= yythunkpos;  if (!yymatchChar(' ')) goto l71;  goto l68;
  l71:;	  yypos= yypos71; yythunkpos= yythunkpos71;
  }  if (!yymatchDot()) goto l68;
  l69:;	
  {  int yypos70= yypos, yythunkpos70= yythunkpos;
  {  int yypos72= yypos, yythunkpos72= yythunkpos;  if (!yymatchChar(' ')) goto l72;  goto l70;
  l72:;	  yypos= yypos72; yythunkpos= yythunkpos72;
  }  if (!yymatchDot()) goto l70;  goto l69;
  l70:;	  yypos= yypos70; yythunkpos= yythunkpos70;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l68;  yyDo(yy_1_link_url, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "link_url", yyunmatched()));
  return 1;
  l68:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "link_url", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_url()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "url"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l73;
  {  int yypos74= yypos, yythunkpos74= yythunkpos;  if (!yymatchString("http")) goto l75;  goto l74;
  l75:;	  yypos= yypos74; yythunkpos= yythunkpos74;  if (!yymatchString("https")) goto l76;  goto l74;
  l76:;	  yypos= yypos74; yythunkpos= yythunkpos74;  if (!yymatchString("ftp")) goto l73;
  }
  l74:;	  yyText(yybegin, yyend);  if (!(YY_END)) goto l73;  yyDo(yy_1_url, yybegin, yyend);  if (!yymatchString("://")) goto l73;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l73;
  l77:;	
  {  int yypos78= yypos, yythunkpos78= yythunkpos;
  {  int yypos79= yypos, yythunkpos79= yythunkpos;  if (!yy_eol()) goto l79;  goto l78;
  l79:;	  yypos= yypos79; yythunkpos= yythunkpos79;
  }
  {  int yypos80= yypos, yythunkpos80= yythunkpos;  if (!yymatchChar(' ')) goto l80;  goto l78;
  l80:;	  yypos= yypos80; yythunkpos= yythunkpos80;
  }  if (!yymatchDot()) goto l78;  goto l77;
  l78:;	  yypos= yypos78; yythunkpos= yythunkpos78;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l73;  yyDo(yy_2_url, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "url", yyunmatched()));
  return 1;
  l73:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "url", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_unnamed_link()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "unnamed_link"));  if (!yymatchChar('[')) goto l81;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l81;
  l82:;	
  {  int yypos83= yypos, yythunkpos83= yythunkpos;
  {  int yypos84= yypos, yythunkpos84= yythunkpos;  if (!yymatchChar(']')) goto l84;  goto l83;
  l84:;	  yypos= yypos84; yythunkpos= yythunkpos84;
  }  if (!yymatchDot()) goto l83;  goto l82;
  l83:;	  yypos= yypos83; yythunkpos= yythunkpos83;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l81;  if (!yymatchChar(']')) goto l81;  yyDo(yy_1_unnamed_link, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "unnamed_link", yyunmatched()));
  return 1;
  l81:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "unnamed_link", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_named_link()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "named_link"));  if (!yymatchChar('[')) goto l85;  yyDo(yy_1_named_link, yybegin, yyend);  if (!yy_link_url()) goto l85;  yyDo(yy_2_named_link, yybegin, yyend);  if (!yymatchChar(' ')) goto l85;
  l86:;	
  {  int yypos87= yypos, yythunkpos87= yythunkpos;  if (!yymatchChar(' ')) goto l87;  goto l86;
  l87:;	  yypos= yypos87; yythunkpos= yythunkpos87;
  }  if (!yy_link_name()) goto l85;
  l88:;	
  {  int yypos89= yypos, yythunkpos89= yythunkpos;  if (!yy_link_name()) goto l89;  goto l88;
  l89:;	  yypos= yypos89; yythunkpos= yythunkpos89;
  }
  l90:;	
  {  int yypos91= yypos, yythunkpos91= yythunkpos;  if (!yymatchChar(' ')) goto l91;  goto l90;
  l91:;	  yypos= yypos91; yythunkpos= yythunkpos91;
  }  if (!yymatchChar(']')) goto l85;  yyDo(yy_3_named_link, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "named_link", yyunmatched()));
  return 1;
  l85:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "named_link", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_external_link()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "external_link"));
  {  int yypos93= yypos, yythunkpos93= yythunkpos;  if (!yy_named_link()) goto l94;  goto l93;
  l94:;	  yypos= yypos93; yythunkpos= yythunkpos93;  if (!yy_unnamed_link()) goto l95;  goto l93;
  l95:;	  yypos= yypos93; yythunkpos= yythunkpos93;  if (!yy_url()) goto l92;
  }
  l93:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "external_link", yyunmatched()));
  return 1;
  l92:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "external_link", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_simple_link()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "simple_link"));  if (!yymatchString("[[")) goto l96;
  {  int yypos97= yypos, yythunkpos97= yythunkpos;  if (!yymatchChar(':')) goto l97;  goto l98;
  l97:;	  yypos= yypos97; yythunkpos= yythunkpos97;
  }
  l98:;	  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l96;
  l99:;	
  {  int yypos100= yypos, yythunkpos100= yythunkpos;
  {  int yypos101= yypos, yythunkpos101= yythunkpos;  if (!yymatchString("]]")) goto l101;  goto l100;
  l101:;	  yypos= yypos101; yythunkpos= yythunkpos101;
  }  if (!yymatchDot()) goto l100;  goto l99;
  l100:;	  yypos= yypos100; yythunkpos= yythunkpos100;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l96;  yyDo(yy_1_simple_link, yybegin, yyend);  if (!yymatchString("]]")) goto l96;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l96;
  l102:;	
  {  int yypos103= yypos, yythunkpos103= yythunkpos;
  {  int yypos104= yypos, yythunkpos104= yythunkpos;  if (!yymatchChar(' ')) goto l104;  goto l103;
  l104:;	  yypos= yypos104; yythunkpos= yythunkpos104;
  }
  {  int yypos105= yypos, yythunkpos105= yythunkpos;  if (!yy_eol()) goto l105;  goto l103;
  l105:;	  yypos= yypos105; yythunkpos= yythunkpos105;
  }  if (!yymatchDot()) goto l103;  goto l102;
  l103:;	  yypos= yypos103; yythunkpos= yythunkpos103;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l96;  yyDo(yy_2_simple_link, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "simple_link", yyunmatched()));
  return 1;
  l96:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "simple_link", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_renamed_link()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "renamed_link"));  if (!yymatchString("[[")) goto l106;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l106;
  l107:;	
  {  int yypos108= yypos, yythunkpos108= yythunkpos;
  {  int yypos109= yypos, yythunkpos109= yythunkpos;  if (!yymatchChar('|')) goto l109;  goto l108;
  l109:;	  yypos= yypos109; yythunkpos= yythunkpos109;
  }  if (!yymatchDot()) goto l108;  goto l107;
  l108:;	  yypos= yypos108; yythunkpos= yythunkpos108;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l106;  yyDo(yy_1_renamed_link, yybegin, yyend);  if (!yymatchChar('|')) goto l106;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l106;
  l110:;	
  {  int yypos111= yypos, yythunkpos111= yythunkpos;
  {  int yypos112= yypos, yythunkpos112= yythunkpos;  if (!yymatchString("]]")) goto l112;  goto l111;
  l112:;	  yypos= yypos112; yythunkpos= yythunkpos112;
  }  if (!yymatchDot()) goto l111;  goto l110;
  l111:;	  yypos= yypos111; yythunkpos= yythunkpos111;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l106;  yyDo(yy_2_renamed_link, yybegin, yyend);  if (!yymatchString("]]")) goto l106;
  yyprintf((stderr, "  ok   %s @ %s\n", "renamed_link", yyunmatched()));
  return 1;
  l106:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "renamed_link", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_pre_line()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "pre_line"));  if (!yymatchChar(' ')) goto l113;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l113;
  l114:;	
  {  int yypos115= yypos, yythunkpos115= yythunkpos;
  {  int yypos116= yypos, yythunkpos116= yythunkpos;  if (!yy_eol()) goto l116;  goto l115;
  l116:;	  yypos= yypos116; yythunkpos= yythunkpos116;
  }  if (!yymatchDot()) goto l115;  goto l114;
  l115:;	  yypos= yypos115; yythunkpos= yythunkpos115;
  }
  {  int yypos117= yypos, yythunkpos117= yythunkpos;  if (!yy_eol()) goto l118;  goto l117;
  l118:;	  yypos= yypos117; yythunkpos= yythunkpos117;
  {  int yypos119= yypos, yythunkpos119= yythunkpos;  if (!yymatchDot()) goto l119;  goto l113;
  l119:;	  yypos= yypos119; yythunkpos= yythunkpos119;
  }
  }
  l117:;	  yyText(yybegin, yyend);  if (!(YY_END)) goto l113;  yyDo(yy_1_pre_line, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "pre_line", yyunmatched()));
  return 1;
  l113:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "pre_line", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_italic()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "italic"));  if (!yymatchString("''")) goto l120;  yyDo(yy_1_italic, yybegin, yyend);
  l121:;	
  {  int yypos122= yypos, yythunkpos122= yythunkpos;
  {  int yypos123= yypos, yythunkpos123= yythunkpos;  if (!yymatchString("''")) goto l123;  goto l122;
  l123:;	  yypos= yypos123; yythunkpos= yythunkpos123;
  }  if (!yy_wikitext()) goto l122;  goto l121;
  l122:;	  yypos= yypos122; yythunkpos= yythunkpos122;
  }  if (!yymatchString("''")) goto l120;  yyDo(yy_2_italic, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "italic", yyunmatched()));
  return 1;
  l120:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "italic", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_bold()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "bold"));  if (!yymatchString("'''")) goto l124;  yyDo(yy_1_bold, yybegin, yyend);
  l125:;	
  {  int yypos126= yypos, yythunkpos126= yythunkpos;
  {  int yypos127= yypos, yythunkpos127= yythunkpos;  if (!yymatchString("'''")) goto l127;  goto l126;
  l127:;	  yypos= yypos127; yythunkpos= yythunkpos127;
  }  if (!yy_wikitext()) goto l126;  goto l125;
  l126:;	  yypos= yypos126; yythunkpos= yythunkpos126;
  }  if (!yymatchString("'''")) goto l124;  yyDo(yy_2_bold, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "bold", yyunmatched()));
  return 1;
  l124:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "bold", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_bold_italic()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "bold_italic"));  if (!yymatchString("'''''")) goto l128;  yyDo(yy_1_bold_italic, yybegin, yyend);
  l129:;	
  {  int yypos130= yypos, yythunkpos130= yythunkpos;
  {  int yypos131= yypos, yythunkpos131= yythunkpos;  if (!yymatchString("'''''")) goto l131;  goto l130;
  l131:;	  yypos= yypos131; yythunkpos= yythunkpos131;
  }  if (!yy_wikitext()) goto l130;  goto l129;
  l130:;	  yypos= yypos130; yythunkpos= yythunkpos130;
  }  if (!yymatchString("'''''")) goto l128;  yyDo(yy_2_bold_italic, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "bold_italic", yyunmatched()));
  return 1;
  l128:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "bold_italic", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_numbered()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "numbered"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l132;  if (!yymatchChar('#')) goto l132;
  l133:;	
  {  int yypos134= yypos, yythunkpos134= yythunkpos;  if (!yymatchChar('#')) goto l134;  goto l133;
  l134:;	  yypos= yypos134; yythunkpos= yythunkpos134;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l132;  yyDo(yy_1_numbered, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "numbered", yyunmatched()));
  return 1;
  l132:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "numbered", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_numbered_list_entry()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "numbered_list_entry"));  if (!yy_numbered()) goto l135;
  l136:;	
  {  int yypos137= yypos, yythunkpos137= yythunkpos;  if (!yymatchChar(' ')) goto l137;  goto l136;
  l137:;	  yypos= yypos137; yythunkpos= yythunkpos137;
  }
  l138:;	
  {  int yypos139= yypos, yythunkpos139= yythunkpos;
  {  int yypos140= yypos, yythunkpos140= yythunkpos;  if (!yy_eol()) goto l140;  goto l139;
  l140:;	  yypos= yypos140; yythunkpos= yythunkpos140;
  }  if (!yy_wikitext()) goto l139;  goto l138;
  l139:;	  yypos= yypos139; yythunkpos= yythunkpos139;
  }
  {  int yypos141= yypos, yythunkpos141= yythunkpos;  if (!yy_eol()) goto l141;  goto l142;
  l141:;	  yypos= yypos141; yythunkpos= yythunkpos141;
  }
  l142:;	  yyDo(yy_1_numbered_list_entry, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "numbered_list_entry", yyunmatched()));
  return 1;
  l135:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "numbered_list_entry", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_bullet()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "bullet"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l143;  if (!yymatchChar('*')) goto l143;
  l144:;	
  {  int yypos145= yypos, yythunkpos145= yythunkpos;  if (!yymatchChar('*')) goto l145;  goto l144;
  l145:;	  yypos= yypos145; yythunkpos= yythunkpos145;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l143;  yyDo(yy_1_bullet, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "bullet", yyunmatched()));
  return 1;
  l143:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "bullet", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_bullet_list_entry()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "bullet_list_entry"));  if (!yy_bullet()) goto l146;
  l147:;	
  {  int yypos148= yypos, yythunkpos148= yythunkpos;  if (!yymatchChar(' ')) goto l148;  goto l147;
  l148:;	  yypos= yypos148; yythunkpos= yythunkpos148;
  }
  l149:;	
  {  int yypos150= yypos, yythunkpos150= yythunkpos;
  {  int yypos151= yypos, yythunkpos151= yythunkpos;  if (!yy_eol()) goto l151;  goto l150;
  l151:;	  yypos= yypos151; yythunkpos= yythunkpos151;
  }  if (!yy_wikitext()) goto l150;  goto l149;
  l150:;	  yypos= yypos150; yythunkpos= yythunkpos150;
  }
  {  int yypos152= yypos, yythunkpos152= yythunkpos;  if (!yy_eol()) goto l153;  goto l152;
  l153:;	  yypos= yypos152; yythunkpos= yythunkpos152;
  {  int yypos154= yypos, yythunkpos154= yythunkpos;  if (!yymatchDot()) goto l154;  goto l146;
  l154:;	  yypos= yypos154; yythunkpos= yythunkpos154;
  }
  }
  l152:;	  yyDo(yy_1_bullet_list_entry, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "bullet_list_entry", yyunmatched()));
  return 1;
  l146:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "bullet_list_entry", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_numbered_list()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "numbered_list"));  yyDo(yy_1_numbered_list, yybegin, yyend);  if (!yy_numbered_list_entry()) goto l155;
  l156:;	
  {  int yypos157= yypos, yythunkpos157= yythunkpos;  if (!yy_numbered_list_entry()) goto l157;  goto l156;
  l157:;	  yypos= yypos157; yythunkpos= yythunkpos157;
  }  yyDo(yy_2_numbered_list, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "numbered_list", yyunmatched()));
  return 1;
  l155:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "numbered_list", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_bullet_list()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "bullet_list"));  yyDo(yy_1_bullet_list, yybegin, yyend);  if (!yy_bullet_list_entry()) goto l158;
  l159:;	
  {  int yypos160= yypos, yythunkpos160= yythunkpos;  if (!yy_bullet_list_entry()) goto l160;  goto l159;
  l160:;	  yypos= yypos160; yythunkpos= yythunkpos160;
  }  yyDo(yy_2_bullet_list, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "bullet_list", yyunmatched()));
  return 1;
  l158:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "bullet_list", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_heading_text()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "heading_text"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l161;
  l162:;	
  {  int yypos163= yypos, yythunkpos163= yythunkpos;
  {  int yypos164= yypos, yythunkpos164= yythunkpos;  if (!yy_heading_marker()) goto l164;  goto l163;
  l164:;	  yypos= yypos164; yythunkpos= yythunkpos164;
  }
  {  int yypos165= yypos, yythunkpos165= yythunkpos;  if (!yy_formatting()) goto l166;  goto l165;
  l166:;	  yypos= yypos165; yythunkpos= yythunkpos165;  if (!yy_anything_else()) goto l163;
  }
  l165:;	  goto l162;
  l163:;	  yypos= yypos163; yythunkpos= yythunkpos163;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l161;  yyDo(yy_1_heading_text, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "heading_text", yyunmatched()));
  return 1;
  l161:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "heading_text", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_heading_marker()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "heading_marker"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l167;  if (!yymatchChar('=')) goto l167;  if (!yymatchChar('=')) goto l167;
  l168:;	
  {  int yypos169= yypos, yythunkpos169= yythunkpos;  if (!yymatchChar('=')) goto l169;  goto l168;
  l169:;	  yypos= yypos169; yythunkpos= yythunkpos169;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l167;  yyDo(yy_1_heading_marker, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "heading_marker", yyunmatched()));
  return 1;
  l167:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "heading_marker", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_eol()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "eol"));  if (!yymatchChar('\n')) goto l170;  yyDo(yy_1_eol, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "eol", yyunmatched()));
  return 1;
  l170:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "eol", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_anything_else()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "anything_else"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l171;
  {  int yypos172= yypos, yythunkpos172= yythunkpos;  if (!yy_eol()) goto l172;  goto l171;
  l172:;	  yypos= yypos172; yythunkpos= yythunkpos172;
  }  if (!yymatchDot()) goto l171;  yyText(yybegin, yyend);  if (!(YY_END)) goto l171;  yyDo(yy_1_anything_else, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "anything_else", yyunmatched()));
  return 1;
  l171:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "anything_else", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_table()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "table"));  if (!yymatchString("{|")) goto l173;  yyDo(yy_1_table, yybegin, yyend);  if (!yy_eol()) goto l173;  if (!yy_table_body()) goto l173;  if (!yymatchString("|}")) goto l173;
  {  int yypos174= yypos, yythunkpos174= yythunkpos;  if (!yy_eol()) goto l175;  goto l174;
  l175:;	  yypos= yypos174; yythunkpos= yythunkpos174;
  {  int yypos176= yypos, yythunkpos176= yythunkpos;  if (!yymatchDot()) goto l176;  goto l173;
  l176:;	  yypos= yypos176; yythunkpos= yythunkpos176;
  }
  }
  l174:;	  yyDo(yy_2_table, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "table", yyunmatched()));
  return 1;
  l173:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "table", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_link()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "link"));
  {  int yypos178= yypos, yythunkpos178= yythunkpos;  if (!yy_renamed_link()) goto l179;  goto l178;
  l179:;	  yypos= yypos178; yythunkpos= yythunkpos178;  if (!yy_simple_link()) goto l180;  goto l178;
  l180:;	  yypos= yypos178; yythunkpos= yythunkpos178;  if (!yy_external_link()) goto l177;
  }
  l178:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "link", yyunmatched()));
  return 1;
  l177:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "link", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_image()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "image"));
  {  int yypos182= yypos, yythunkpos182= yythunkpos;  if (!yy_image_with_alt()) goto l183;  goto l182;
  l183:;	  yypos= yypos182; yythunkpos= yythunkpos182;  if (!yy_plain_image()) goto l181;
  }
  l182:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "image", yyunmatched()));
  return 1;
  l181:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "image", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_formatting()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "formatting"));
  {  int yypos185= yypos, yythunkpos185= yythunkpos;  if (!yy_bold_italic()) goto l186;  goto l185;
  l186:;	  yypos= yypos185; yythunkpos= yythunkpos185;  if (!yy_bold()) goto l187;  goto l185;
  l187:;	  yypos= yypos185; yythunkpos= yythunkpos185;  if (!yy_italic()) goto l184;
  }
  l185:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "formatting", yyunmatched()));
  return 1;
  l184:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "formatting", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_list()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "list"));
  {  int yypos189= yypos, yythunkpos189= yythunkpos;  if (!yy_bullet_list()) goto l190;  goto l189;
  l190:;	  yypos= yypos189; yythunkpos= yythunkpos189;  if (!yy_numbered_list()) goto l188;
  }
  l189:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "list", yyunmatched()));
  return 1;
  l188:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "list", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_indentation()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "indentation"));  yyText(yybegin, yyend);  if (!( start_of_line )) goto l191;  if (!yymatchChar(':')) goto l191;  yyDo(yy_1_indentation, yybegin, yyend);  if (!yy_wikitext()) goto l191;
  yyprintf((stderr, "  ok   %s @ %s\n", "indentation", yyunmatched()));
  return 1;
  l191:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "indentation", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_heading()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "heading"));  if (!yy_heading_marker()) goto l192;  yyDo(yy_1_heading, yybegin, yyend);
  l193:;	
  {  int yypos194= yypos, yythunkpos194= yythunkpos;  if (!yymatchChar(' ')) goto l194;  goto l193;
  l194:;	  yypos= yypos194; yythunkpos= yythunkpos194;
  }  if (!yy_heading_text()) goto l192;  if (!yy_heading_marker()) goto l192;  yyDo(yy_2_heading, yybegin, yyend);
  l195:;	
  {  int yypos196= yypos, yythunkpos196= yythunkpos;  if (!yymatchChar(' ')) goto l196;  goto l195;
  l196:;	  yypos= yypos196; yythunkpos= yythunkpos196;
  }
  {  int yypos197= yypos, yythunkpos197= yythunkpos;  if (!yy_eol()) goto l198;  goto l197;
  l198:;	  yypos= yypos197; yythunkpos= yythunkpos197;
  {  int yypos199= yypos, yythunkpos199= yythunkpos;  if (!yymatchDot()) goto l199;  goto l192;
  l199:;	  yypos= yypos199; yythunkpos= yythunkpos199;
  }
  }
  l197:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "heading", yyunmatched()));
  return 1;
  l192:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "heading", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_horizontal_line()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "horizontal_line"));  if (!yymatchString("----")) goto l200;
  {  int yypos201= yypos, yythunkpos201= yythunkpos;  if (!yy_eol()) goto l202;  goto l201;
  l202:;	  yypos= yypos201; yythunkpos= yythunkpos201;
  {  int yypos203= yypos, yythunkpos203= yythunkpos;  if (!yymatchDot()) goto l203;  goto l200;
  l203:;	  yypos= yypos203; yythunkpos= yythunkpos203;
  }
  }
  l201:;	  yyDo(yy_1_horizontal_line, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "horizontal_line", yyunmatched()));
  return 1;
  l200:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "horizontal_line", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_paragraph()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "paragraph"));  yyDo(yy_1_paragraph, yybegin, yyend);  if (!yy_wikitext()) goto l204;  if (!yy_eol()) goto l204;  if (!yy_eol()) goto l204;  yyDo(yy_2_paragraph, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "paragraph", yyunmatched()));
  return 1;
  l204:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "paragraph", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_wikitext()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "wikitext"));
  {  int yypos206= yypos, yythunkpos206= yythunkpos;  if (!yy_heading()) goto l207;  goto l206;
  l207:;	  yypos= yypos206; yythunkpos= yythunkpos206;  if (!yy_indentation()) goto l208;  goto l206;
  l208:;	  yypos= yypos206; yythunkpos= yythunkpos206;  if (!yy_list()) goto l209;  goto l206;
  l209:;	  yypos= yypos206; yythunkpos= yythunkpos206;  if (!yy_formatting()) goto l210;  goto l206;
  l210:;	  yypos= yypos206; yythunkpos= yythunkpos206;  if (!yy_image()) goto l211;  goto l206;
  l211:;	  yypos= yypos206; yythunkpos= yythunkpos206;  if (!yy_link()) goto l212;  goto l206;
  l212:;	  yypos= yypos206; yythunkpos= yythunkpos206;  if (!yy_table()) goto l213;  goto l206;
  l213:;	  yypos= yypos206; yythunkpos= yythunkpos206;  if (!yy_anything_else()) goto l214;  goto l206;
  l214:;	  yypos= yypos206; yythunkpos= yythunkpos206;  if (!yy_eol()) goto l205;
  }
  l206:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "wikitext", yyunmatched()));
  return 1;
  l205:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "wikitext", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_wikitext_line()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "wikitext_line"));
  {  int yypos216= yypos, yythunkpos216= yythunkpos;  if (!yy_paragraph()) goto l217;  goto l216;
  l217:;	  yypos= yypos216; yythunkpos= yythunkpos216;  if (!yy_horizontal_line()) goto l215;
  }
  l216:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "wikitext_line", yyunmatched()));
  return 1;
  l215:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "wikitext_line", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_pre_block()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "pre_block"));  yyText(yybegin, yyend);  if (!( start_of_line )) goto l218;  yyDo(yy_1_pre_block, yybegin, yyend);  if (!yy_pre_line()) goto l218;
  l219:;	
  {  int yypos220= yypos, yythunkpos220= yythunkpos;  if (!yy_pre_line()) goto l220;  goto l219;
  l220:;	  yypos= yypos220; yythunkpos= yythunkpos220;
  }  yyDo(yy_2_pre_block, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "pre_block", yyunmatched()));
  return 1;
  l218:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "pre_block", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_page()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "page"));
  {  int yypos222= yypos, yythunkpos222= yythunkpos;  if (!yy_pre_block()) goto l223;  goto l222;
  l223:;	  yypos= yypos222; yythunkpos= yythunkpos222;  if (!yy_wikitext_line()) goto l224;  goto l222;
  l224:;	  yypos= yypos222; yythunkpos= yythunkpos222;  if (!yy_wikitext()) goto l221;
  }
  l222:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "page", yyunmatched()));
  return 1;
  l221:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "page", yyunmatched()));
  return 0;
}

#ifndef YY_PART

typedef int (*yyrule)();

YY_PARSE(int) YYPARSEFROM(yyrule yystart)
{
  int yyok;
  if (!yybuflen)
    {
      yybuflen= 1024;
      yybuf= malloc(yybuflen);
      yytextlen= 1024;
      yytext= malloc(yytextlen);
      yythunkslen= 32;
      yythunks= malloc(sizeof(yythunk) * yythunkslen);
      yyvalslen= 32;
      yyvals= malloc(sizeof(YYSTYPE) * yyvalslen);
      yybegin= yyend= yypos= yylimit= yythunkpos= 0;
    }
  yybegin= yyend= yypos;
  yythunkpos= 0;
  yyval= yyvals;
  yyok= yystart();
  if (yyok) yyDone();
  yyCommit();
  return yyok;
  (void)yyrefill;
  (void)yymatchDot;
  (void)yymatchChar;
  (void)yymatchString;
  (void)yymatchClass;
  (void)yyDo;
  (void)yyText;
  (void)yyDone;
  (void)yyCommit;
  (void)yyAccept;
  (void)yyPush;
  (void)yyPop;
  (void)yySet;
  (void)yytextmax;
}

YY_PARSE(int) YYPARSE(void)
{
  return YYPARSEFROM(yy_page);
}

#endif


int main() {
	tag_content = (char *)malloc(2 * MBYTE);
	while(yyparse()) {}
	
	return 0;
}

